"""Typed surface for Cimba random draws."""

from collections.abc import Iterable


class AliasSampler:
    """Reusable Vose alias sampler for non-uniform discrete probabilities."""

    def __init__(self, probabilities: Iterable[float]) -> None: ...
    def __enter__(self) -> AliasSampler: ...
    def __exit__(self, exc_type: object, exc: object, tb: object) -> bool: ...
    def __len__(self) -> int: ...
    def sample(self) -> int: ...
    def close(self) -> None: ...


def hwseed() -> int: ...
def seed(value: int | None = None) -> int: ...
def current_seed() -> int: ...
def random_u64() -> int: ...
def fmix64(seed: int, nonce: int) -> int: ...
def uniform(min: float = 0.0, max: float = 1.0) -> float: ...
def triangular(min: float, mode: float, max: float) -> float: ...
def normal(mu: float = 0.0, sigma: float = 1.0) -> float: ...
def lognormal(m: float, s: float) -> float: ...
def logistic(m: float, s: float) -> float: ...
def cauchy(mode: float, scale: float) -> float: ...
def exponential(mean: float = 1.0) -> float: ...
def erlang(k: int, mean: float) -> float: ...
def hypoexponential(means: Iterable[float]) -> float: ...
def hyperexponential(
    means: Iterable[float],
    probabilities: Iterable[float],
) -> float: ...
def gamma(shape: float, scale: float = 1.0) -> float: ...
def beta(
    a: float,
    b: float,
    min: float = 0.0,
    max: float = 1.0,
) -> float: ...
def pert(min: float, mode: float, max: float) -> float: ...
def pert_mod(min: float, mode: float, max: float, lambda_: float) -> float: ...
def weibull(shape: float, scale: float) -> float: ...
def pareto(shape: float, mode: float) -> float: ...
def chi_squared(k: float) -> float: ...
def f_dist(a: float, b: float) -> float: ...
def student_t(v: float, m: float = 0.0, s: float = 1.0) -> float: ...
def rayleigh(s: float) -> float: ...
def dice(min: int, max: int) -> int: ...
def bernoulli(p: float) -> bool: ...
def geometric(p: float) -> int: ...
def binomial(n: int, p: float) -> int: ...
def negative_binomial(m: int, p: float) -> int: ...
def poisson(r: float) -> int: ...
def categorical(probabilities: Iterable[float]) -> int: ...
