"""Random draws for compiled model callbacks and their Numba helpers."""

from collections.abc import Iterable


def uniform(min: float = 0.0, max: float = 1.0) -> float: ...
def triangular(min: float, mode: float, max: float) -> float: ...
def normal(mu: float = 0.0, sigma: float = 1.0) -> float: ...
def lognormal(m: float, s: float) -> float: ...
def logistic(m: float, s: float) -> float: ...
def cauchy(mode: float, scale: float) -> float: ...
def exponential(mean: float = 1.0) -> float: ...
def erlang(k: int, mean: float) -> float: ...
def hypoexponential(means: Iterable[float]) -> float: ...
def hyperexponential(
    means: Iterable[float],
    probabilities: Iterable[float],
) -> float: ...
def gamma(shape: float, scale: float = 1.0) -> float: ...
def beta(
    a: float,
    b: float,
    min: float = 0.0,
    max: float = 1.0,
) -> float: ...
def pert(min: float, mode: float, max: float) -> float: ...
def pert_mod(min: float, mode: float, max: float, lambda_: float) -> float: ...
def weibull(shape: float, scale: float) -> float: ...
def pareto(shape: float, mode: float) -> float: ...
def chi_squared(k: float) -> float: ...
def f_dist(a: float, b: float) -> float: ...
def student_t(v: float, m: float = 0.0, s: float = 1.0) -> float: ...
def rayleigh(s: float) -> float: ...
def dice(min: int, max: int) -> int: ...
def bernoulli(p: float) -> bool: ...
def geometric(p: float) -> int: ...
def binomial(n: int, p: float) -> int: ...
def negative_binomial(m: int, p: float) -> int: ...
def poisson(r: float) -> int: ...
def categorical(probabilities: Iterable[float]) -> int: ...
