"""Sphinx directive that draws a model with ``cimba.diagrams`` at build time.

Usage::

   .. cimba-diagram:: tutorial.tut_1_1:MM1
      :kind: process          # or "structure"
      :direction: LR          # Mermaid flowchart direction (default TD)
      :state:                 # include Param/State/Output writes
      :hooks:                 # include on_start/on_end hooks
      :caption: The M/M/1 model
      :layout: elk            # or dagre (Mermaid's default); elk is the default here

The argument names a module and a callable returning a configured model (a
model class works: it is called with no arguments). The Mermaid text is
generated by the library and rendered by ``sphinxcontrib.mermaid``, so the
pictures always match the code.
"""

from importlib import import_module

from docutils import nodes
from docutils.parsers.rst import Directive, directives
from docutils.statemachine import StringList


class CimbaDiagram(Directive):
    required_arguments = 1
    has_content = False
    option_spec = {
        "kind": lambda value: directives.choice(value, ("process", "structure")),
        "direction": lambda value: directives.choice(value, ("td", "tb", "lr", "rl", "bt")).upper(),
        "state": directives.flag,
        "hooks": directives.flag,
        "caption": directives.unchanged,
        "layout": lambda value: directives.choice(value, ("elk", "dagre")),
    }

    def run(self):
        from cimba import diagrams

        module_name, _, factory_name = self.arguments[0].partition(":")
        factory = getattr(import_module(module_name), factory_name)
        model = factory()
        if self.options.get("kind", "process") == "structure":
            graph = diagrams.structure(model)
        else:
            graph = diagrams.process_graph(model, state="state" in self.options,
                                           hooks="hooks" in self.options)
        text = graph.to_mermaid(self.options.get("direction", "TD"))
        lines = [".. mermaid::"]
        if "caption" in self.options:
            lines.append(f"   :caption: {self.options['caption']}")
        lines.append("")
        layout = self.options.get("layout", "elk")
        lines.extend(["   ---", "   config:", f"     layout: {layout}", "   ---"])
        lines.extend("   " + line for line in text.splitlines())
        content = StringList(lines, source=self.state_machine.input_lines.source(0))
        holder = nodes.section()
        holder.document = self.state.document
        self.state.nested_parse(content, self.content_offset, holder)
        return holder.children


def setup(app):
    app.add_directive("cimba-diagram", CimbaDiagram)
    return {"parallel_read_safe": True, "parallel_write_safe": True}
