"""Type stubs for the compiled ``cimba._cimba`` cffi extension module."""

from typing import Any

from _cffi_backend import FFI

class _Lib:
    """The cdef'd symbols exposed through cffi (see _cffi_build.py)."""

    def cimba_version(self) -> Any: ...  # cdata char *
    def cimba_run_experiment(self, trials: Any, num_trials: int,
                             trial_struct_size: int,
                             trial_func: Any) -> None: ...
    def cmb_random_hwseed(self) -> int: ...
    def cpy_process_sizeof(self) -> int: ...
    def cpy_history_capture_store_create(self, num_trials: int,
                                         num_slots: int) -> Any: ...
    def cpy_history_capture_store_destroy(self, store: Any) -> None: ...
    def cpy_history_capture_store_count(self, store: Any, trial: int,
                                        slot: int) -> int: ...
    def cpy_history_capture_store_data(self, store: Any, trial: int,
                                       slot: int) -> Any: ...
    def cpy_logger_flags_on(self, flags: int) -> None: ...
    def cpy_logger_flags_off(self, flags: int) -> None: ...
    def cmb_logger_flags_off(self, flags: int) -> None: ...

ffi: FFI
lib: _Lib
