from collections.abc import Callable
from typing import Any

UNLIMITED: int

SUCCESS: int
PREEMPTED: int
INTERRUPTED: int
STOPPED: int
CANCELLED: int
TIMEOUT: int

PROCESS_CREATED: int
PROCESS_RUNNING: int
PROCESS_FINISHED: int

LOGGER_FATAL: int
LOGGER_ERROR: int
LOGGER_WARNING: int
LOGGER_INFO: int

def native_version() -> str: ...
def logger_flags_on(flags: int) -> None: ...
def logger_flags_off(flags: int) -> None: ...

def hwseed() -> int: ...
def seed(value: int | None = None) -> int: ...
def current_seed() -> int: ...
def random() -> float: ...
def random_u64() -> int: ...
def fmix64(seed: int, nonce: int) -> int: ...
def uniform(min: float, max: float) -> float: ...
def triangular(min: float, mode: float, max: float) -> float: ...
def normal(mu: float = 0.0, sigma: float = 1.0) -> float: ...
def exponential(mean: float) -> float: ...
def gamma(shape: float, scale: float = 1.0) -> float: ...
def beta(a: float, b: float, min: float = 0.0, max: float = 1.0) -> float: ...
def pert(min: float, mode: float, max: float) -> float: ...
def pert_mod(min: float, mode: float, max: float, lambda_: float) -> float: ...
def dice(min: int, max: int) -> int: ...
def flip() -> bool: ...
def bernoulli(p: float) -> bool: ...

def time() -> float: ...
def hold(duration: float) -> int: ...
def yield_process() -> int: ...
def process_exit(value: object | None = None) -> None: ...
def current_process() -> Process | None: ...

class Simulation:
    seed_used: int
    def __init__(self, start_time: float = 0.0, seed: int | None = None, log_info: bool = False) -> None: ...
    def __enter__(self) -> Simulation: ...
    def __exit__(self, exc_type: object, exc: object, tb: object) -> bool: ...
    @property
    def closed(self) -> bool: ...
    @property
    def now(self) -> float: ...
    @property
    def event_count(self) -> int: ...
    def stop_at(self, when: float, priority: int = 0) -> int: ...
    def clear(self) -> None: ...
    def execute_next(self) -> bool: ...
    def execute(self) -> None: ...
    def close(self) -> None: ...

class Process:
    def __init__(
        self,
        name: str,
        func: Callable[[Process, Any], object],
        context: object | None = None,
        priority: int = 0,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def priority(self) -> int: ...
    @priority.setter
    def priority(self, value: int) -> None: ...
    @property
    def status(self) -> int: ...
    def start(self) -> Process: ...
    def stop(self) -> int: ...
    def interrupt(self, signal: int = INTERRUPTED, priority: int = 0) -> None: ...
    def resume(self, signal: int = SUCCESS) -> None: ...
    def wait(self) -> int: ...
    def timer_add(self, duration: float, signal: int = TIMEOUT) -> int: ...
    def timer_set(self, duration: float, signal: int = TIMEOUT) -> int: ...
    def timer_cancel(self, handle: int) -> bool: ...
    def timers_clear(self) -> None: ...
    def exit_value(self) -> object | None: ...
    def close(self) -> None: ...

class Buffer:
    def __init__(self, name: str, capacity: int | None = None) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def capacity(self) -> int: ...
    @property
    def level(self) -> int: ...
    @property
    def space(self) -> int: ...
    def put(self, amount: int = 1) -> tuple[int, int]: ...
    def get(self, amount: int = 1) -> tuple[int, int]: ...
    def start_recording(self) -> None: ...
    def stop_recording(self) -> None: ...
    def history(self) -> TimeSeries: ...
    def close(self) -> None: ...

class ObjectQueue:
    def __init__(self, name: str, capacity: int | None = None) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def capacity(self) -> int: ...
    @property
    def length(self) -> int: ...
    @property
    def space(self) -> int: ...
    def put(self, obj: object) -> int: ...
    def get(self) -> tuple[int, object | None]: ...
    def position(self, obj: object) -> int: ...
    def start_recording(self) -> None: ...
    def stop_recording(self) -> None: ...
    def history(self) -> TimeSeries: ...
    def close(self) -> None: ...

class PriorityQueue:
    def __init__(self, name: str, capacity: int | None = None) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def capacity(self) -> int: ...
    @property
    def length(self) -> int: ...
    @property
    def space(self) -> int: ...
    def put(self, obj: object, priority: int = 0) -> tuple[int, int]: ...
    def get(self) -> tuple[int, object | None]: ...
    def position(self, handle: int) -> int: ...
    def cancel(self, handle: int) -> bool: ...
    def reprioritize(self, handle: int, priority: int) -> None: ...
    def start_recording(self) -> None: ...
    def stop_recording(self) -> None: ...
    def history(self) -> TimeSeries: ...
    def close(self) -> None: ...

class Resource:
    def __init__(self, name: str) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def in_use(self) -> int: ...
    @property
    def available(self) -> int: ...
    def acquire(self) -> int: ...
    def preempt(self) -> int: ...
    def release(self) -> None: ...
    def held_by(self, process: Process) -> int: ...
    def start_recording(self) -> None: ...
    def stop_recording(self) -> None: ...
    def history(self) -> TimeSeries: ...
    def close(self) -> None: ...

class ResourcePool:
    def __init__(self, name: str, capacity: int) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def capacity(self) -> int: ...
    @property
    def in_use(self) -> int: ...
    @property
    def available(self) -> int: ...
    def acquire(self, amount: int = 1) -> int: ...
    def preempt(self, amount: int = 1) -> int: ...
    def release(self, amount: int = 1) -> None: ...
    def held_by(self, process: Process) -> int: ...
    def start_recording(self) -> None: ...
    def stop_recording(self) -> None: ...
    def history(self) -> TimeSeries: ...
    def close(self) -> None: ...

class Condition:
    def __init__(self, name: str) -> None: ...
    def wait(self, predicate: Callable[[Process | None, Any], bool], context: object | None = None) -> int: ...
    def signal(self) -> int: ...
    def close(self) -> None: ...

class DataSummary:
    def __init__(self) -> None: ...
    def add(self, value: float) -> int: ...
    @property
    def count(self) -> int: ...
    @property
    def min(self) -> float: ...
    @property
    def max(self) -> float: ...
    @property
    def mean(self) -> float: ...
    @property
    def variance(self) -> float: ...
    @property
    def stddev(self) -> float: ...
    @property
    def skewness(self) -> float: ...
    @property
    def kurtosis(self) -> float: ...
    def close(self) -> None: ...

class WeightedSummary:
    def __init__(self) -> None: ...
    def add(self, value: float, weight: float = 1.0) -> int: ...
    @property
    def count(self) -> int: ...
    @property
    def weight_sum(self) -> float: ...
    @property
    def min(self) -> float: ...
    @property
    def max(self) -> float: ...
    @property
    def mean(self) -> float: ...
    @property
    def variance(self) -> float: ...
    @property
    def stddev(self) -> float: ...
    @property
    def skewness(self) -> float: ...
    @property
    def kurtosis(self) -> float: ...
    def close(self) -> None: ...

class Dataset:
    def __init__(self) -> None: ...
    def add(self, value: float) -> int: ...
    def values(self) -> list[float]: ...
    def summary(self) -> DataSummary: ...
    @property
    def count(self) -> int: ...
    @property
    def min(self) -> float: ...
    @property
    def max(self) -> float: ...
    @property
    def median(self) -> float: ...
    def close(self) -> None: ...

class TimeSeries:
    def __init__(self) -> None: ...
    def add(self, value: float, time: float) -> int: ...
    def finalize(self, time: float) -> int: ...
    def values(self) -> list[tuple[float, float, float]]: ...
    def summary(self) -> WeightedSummary: ...
    @property
    def count(self) -> int: ...
    @property
    def min(self) -> float: ...
    @property
    def max(self) -> float: ...
    @property
    def median(self) -> float: ...
    def close(self) -> None: ...
