"""Type stubs for the native facade's CFFI interface."""

from typing import Any

from _cffi_backend import FFI

class _Lib:
    """The native symbols declared in _cimba.py."""

    def cimba_version(self) -> Any: ...  # cdata char *
    def cimba_run(self, trials: Any, num_trials: int,
                             trial_struct_size: int,
                             trial_func: Any) -> int: ...
    def cimba_threads_use(self, n_threads: int) -> int: ...
    def cpy_logger_flags_on(self, flags: int) -> None: ...
    def cpy_logger_flags_off(self, flags: int) -> None: ...
    def cmb_random_hwseed(self) -> int: ...
    def cpy_process_sizeof(self) -> int: ...
    def cpy_history_capture_store_create(self, num_trials: int,
                                         num_slots: int) -> Any: ...
    def cpy_history_capture_store_destroy(self, store: Any) -> None: ...
    def cpy_history_capture_store_count(self, store: Any, trial: int,
                                        slot: int) -> int: ...
    def cpy_history_capture_store_data(self, store: Any, trial: int,
                                       slot: int) -> Any: ...

ffi: FFI
lib: _Lib
