"""Per-trial inputs of an experiment: design points, seeds, and traces.

``experiment()`` expands its keyword arguments into one record per trial:
parameter values form a cross product of design points (replications
innermost), every trial draws its own seed, and each ``sim.Trace`` field
receives one float64 row per trial (and per component slot) -- given
directly as arrays or generated by a callable from ``trace_rng()``.
"""

import hashlib
import inspect
from collections.abc import Callable, Sequence
from typing import Any

import numpy as np

from ._cimba import lib

def _as_param_axis(
    value: Any,
    shape: tuple[int, ...] | None,
    name: str,
) -> np.ndarray:
    arr = np.asarray(value, dtype=np.float64)
    if shape is None:
        return np.atleast_1d(arr).reshape(-1)
    if arr.ndim == 0:
        return np.full((1, *shape), float(arr), dtype=np.float64)
    if arr.shape == shape:
        return np.ascontiguousarray(arr.reshape((1, *shape)),
                                    dtype=np.float64)
    if arr.ndim == len(shape) + 1 and arr.shape[1:] == shape:
        return np.ascontiguousarray(arr, dtype=np.float64)
    raise ValueError(
        f"parameter '{name}': expected a scalar, shape {shape}, or "
        f"(n, {', '.join(str(dim) for dim in shape)}) design rows; "
        f"got shape {arr.shape}")


def _n_design_points(axes: Sequence[np.ndarray]) -> int:
    """Design points in the cross product of the parameter axes; a
    scalar parameter is a length-1 axis and contributes a factor of 1."""
    n_points = 1
    for axis in axes:
        n_points *= axis.shape[0]
    return n_points


def _as_trace_rows(value: Any, n_trials: int, name: str) -> list[np.ndarray]:
    """Normalize a Trace value into one contiguous float64 row per trial:
    a 1-D array is shared by every trial, a 2-D array maps row i to trial
    i, and a sequence of 1-D arrays gives ragged per-trial traces."""
    if not isinstance(value, np.ndarray):
        try:
            value = np.asarray(value, dtype=np.float64)
        except (ValueError, TypeError):
            # Ragged: a sequence of per-trial 1-D arrays
            rows = [np.ascontiguousarray(row, dtype=np.float64)
                    for row in value]
            if len(rows) != n_trials:
                raise ValueError(
                    f"trace '{name}': expected {n_trials} per-trial "
                    f"arrays (one per trial), got {len(rows)}") from None
            for row in rows:
                if row.ndim != 1:
                    raise ValueError(f"trace '{name}': per-trial arrays "
                                     "must be 1-D") from None
            return rows
    arr = np.ascontiguousarray(value, dtype=np.float64)
    if arr.ndim == 1:
        return [arr] * n_trials
    if arr.ndim == 2:
        if arr.shape[0] != n_trials:
            raise ValueError(
                f"trace '{name}': expected {n_trials} rows (one per "
                f"trial, design-point-major with replications innermost), "
                f"got {arr.shape[0]}")
        return list(arr)
    raise ValueError(f"trace '{name}': expected a 1-D array (shared), a "
                     "2-D array (row per trial), or a sequence of 1-D "
                     "arrays")


def _trace_generator_wants_index(fn: Callable[..., Any]) -> bool:
    try:
        required = [p for p in inspect.signature(fn).parameters.values()
                    if p.kind in (p.POSITIONAL_ONLY,
                                  p.POSITIONAL_OR_KEYWORD)
                    and p.default is p.empty]
    except (TypeError, ValueError):
        return False
    return len(required) >= 2


def _draw_trial_seeds(seed: int | None, n_trials: int) -> np.ndarray:
    """The per-trial seed draw shared by experiment() and trial_seeds():
    one uint64 per trial seeds the in-sim RNG and, through trace_rng(),
    any callable trace generators."""
    rng = np.random.default_rng(
        seed if seed is not None else int(lib.cmb_random_hwseed()))
    return rng.integers(1, np.iinfo(np.uint64).max, size=n_trials,
                        dtype=np.uint64)


def trace_rng(trial_seed: int, field_name: str) -> np.random.Generator:
    """The generator a callable trace field sees for one trial: seeded
    from the trial's own cimba seed plus the field name, so a single
    experiment seed reproduces both the simulation streams and the
    generated traces, each trace field draws an independent stream, and
    any trial's trace can be regenerated post-hoc from its recorded
    ``exp["seed"]``.

    A callable with a ``trace_rng_name`` attribute uses that string
    instead of its field name -- callables sharing the tag receive
    identical per-trial generators, which lets one joint resample drive
    several trace fields with preserved cross-correlation."""
    tag = int.from_bytes(
        hashlib.sha256(field_name.encode()).digest()[:8], "little")
    return np.random.default_rng([int(trial_seed), tag])


def _generate_trace_rows(fn: Callable[..., Any], seeds: np.ndarray,
                         name: str) -> list[np.ndarray]:
    """Call a trace generator once per trial with that trial's
    trace_rng(); ``fn(rng)`` or ``fn(rng, trial_index)``."""
    wants_index = _trace_generator_wants_index(fn)
    rows: list[np.ndarray] = []
    tag = getattr(fn, "trace_rng_name", None) or name
    for i, s in enumerate(seeds):
        rng = trace_rng(int(s), tag)
        out = fn(rng, i) if wants_index else fn(rng)
        row = np.ascontiguousarray(out, dtype=np.float64)
        if row.ndim != 1:
            raise ValueError(f"trace '{name}': generator must return a "
                             f"1-D array, got {row.ndim}-D for trial {i}")
        rows.append(row)
    return rows


def _trace_rows_from_value(value: Any, seeds: np.ndarray, name: str,
                           n_trials: int) -> list[np.ndarray]:
    if callable(value):
        return _generate_trace_rows(value, seeds, name)
    return _as_trace_rows(value, n_trials, name)


def _trace_slot_name(name: str, index: int) -> str:
    return f"{name}[{index}]"


def _as_single_trace_row(value: Any, name: str, context: str) -> np.ndarray:
    if callable(value):
        raise ValueError(
            f"trace '{name}': callable values are not valid for {context}")
    row = np.ascontiguousarray(value, dtype=np.float64)
    if row.ndim != 1:
        raise ValueError(
            f"trace '{name}': {context} must be 1-D, got {row.ndim}-D")
    return row


def _trace_grid_shape_error(name: str, n_trials: int, slots: int) -> str:
    return (
        f"trace '{name}': expected a 1-D array shared by every trial and "
        f"component, a 2-D array with {slots} component rows or {n_trials} "
        f"trial rows, a 3-D array with shape ({n_trials}, {slots}, length), "
        "or a sequence of component trace values"
    )


def _as_trace_array_grid(value: Any, n_trials: int, slots: int,
                         name: str) -> list[list[np.ndarray]]:
    arr = np.ascontiguousarray(value, dtype=np.float64)
    if arr.ndim == 1:
        grid = np.broadcast_to(arr, (n_trials, slots, arr.size))
    elif arr.ndim == 2 and arr.shape[0] == slots:
        grid = np.broadcast_to(arr, (n_trials, *arr.shape))
    elif arr.ndim == 2 and arr.shape[0] == n_trials:
        grid = np.broadcast_to(arr[:, None, :], (n_trials, slots, arr.shape[1]))
    elif arr.ndim == 3 and arr.shape[:2] == (n_trials, slots):
        grid = arr
    else:
        raise ValueError(_trace_grid_shape_error(name, n_trials, slots))
    return [[np.ascontiguousarray(row) for row in trial] for trial in grid]


def _trace_slot_rows(
    value: Any, slots: int, name: str, context: str
) -> list[np.ndarray]:
    try:
        values = list(value)
    except TypeError as exc:
        raise ValueError(
            f"trace '{name}': expected {slots} component rows for {context}"
        ) from exc
    if len(values) != slots:
        raise ValueError(
            f"trace '{name}': expected {slots} component rows for {context}"
        )
    return [
        _as_single_trace_row(
            item, _trace_slot_name(name, slot), f"{context}, component {slot}"
        )
        for slot, item in enumerate(values)
    ]


def _as_trace_sequence_grid(value: Any, seeds: np.ndarray, n_trials: int,
                            slots: int, name: str) -> list[list[np.ndarray]]:
    try:
        values = list(value)
    except TypeError as exc:
        raise ValueError(_trace_grid_shape_error(name, n_trials, slots)) \
            from exc

    if len(values) == slots:
        slot_rows = [
            _trace_rows_from_value(slot_value, seeds,
                                   _trace_slot_name(name, slot), n_trials)
            for slot, slot_value in enumerate(values)
        ]
        return [
            [slot_rows[slot][trial] for slot in range(slots)]
            for trial in range(n_trials)
        ]

    if len(values) == n_trials:
        try:
            return [
                _trace_slot_rows(row, slots, name, f"trial {trial}")
                for trial, row in enumerate(values)
            ]
        except ValueError as exc:
            raise ValueError(_trace_grid_shape_error(name, n_trials, slots)) from exc

    raise ValueError(_trace_grid_shape_error(name, n_trials, slots))


def _generate_trace_grid(fn: Callable[..., Any], seeds: np.ndarray,
                         n_trials: int, slots: int,
                         name: str) -> list[list[np.ndarray]]:
    wants_index = _trace_generator_wants_index(fn)
    tag = getattr(fn, "trace_rng_name", None) or name
    rows: list[list[np.ndarray]] = []
    for trial, seed in enumerate(seeds):
        rng = trace_rng(int(seed), tag)
        out = fn(rng, trial) if wants_index else fn(rng)
        try:
            rows.append(_as_trace_array_grid(out, 1, slots, name)[0])
        except ValueError:
            try:
                rows.append(_trace_slot_rows(out, slots, name, f"trial {trial}"))
            except ValueError as exc:
                raise ValueError(
                    f"trace '{name}': generator must return a 1-D array or {slots} component rows for trial {trial}"
                ) from exc
    return rows


def _as_trace_grid(value: Any, seeds: np.ndarray, n_trials: int,
                   slots: int, name: str) -> list[list[np.ndarray]]:
    if slots == 1:
        return [[row] for row in _trace_rows_from_value(
            value, seeds, name, n_trials)]
    if callable(value):
        return _generate_trace_grid(value, seeds, n_trials, slots, name)
    if isinstance(value, np.ndarray):
        return _as_trace_array_grid(value, n_trials, slots, name)
    try:
        return _as_trace_array_grid(value, n_trials, slots, name)
    except (ValueError, TypeError):
        return _as_trace_sequence_grid(value, seeds, n_trials, slots, name)
